[build]
builder = "nixpacks"
buildCommand = "cd server && npm install --legacy-peer-deps && npx prisma generate && cd ../frontend && npm install && npm run build"

[deploy]
startCommand = "cd server && chmod +x setup-production-mcp.sh && ./setup-production-mcp.sh && npm run start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
healthcheckPath = "/api/health"
healthcheckTimeout = 30

[[services]]
name = "server"
port = 3001
internalPort = 3001
targetPort = 3001
protocol = "http"

[[services]]
name = "collector"
port = 8888
internalPort = 8888
targetPort = 8888
protocol = "http"

[env]
NODE_ENV = "production"
SERVER_PORT = "3001"
STORAGE_DIR = "/app/storage"

# Cron jobs can be added here when the job files are created
# Example:
# [[crons]]
# name = "process-documents"
# schedule = "*/5 * * * *"
# command = "cd server && node utils/jobs/processDocuments.js"